# Generated by Django 3.0.9 on 2020-09-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
